name: DevSecOps 2048 Static WebApp

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # SECURITY - Run CodeQL static analysis
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    # SECURITY - Run OWASP dependency check (SCA)
    - name: OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: '2048 Static WebApp'
        path: '.'

    # DEPLOY - Deploy static site to Azure Web App
    - name: Deploy static files to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: '2048webappบอล'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: '.'

